### ISSUE TITLE
Reproducing Figure 6

### ISSUE THREAD

**Issue by shwong-tw** [mcmero/SVclone_Rmarkdown#1]
Dear developer,

I would like to follow the reproducible code and generate Figure 6ab,
however I found that the data utilized was not deposit in the supplementary information (e.g. ccube_out/)
Would you kindly point me to where I can (apply for) access to the data?

Thank you very much

**Comment by shwong-tw** [comment]
Or perhaps a supplementary table including the subclonal fraction and classification of PCAWG patient is enough to reproduce the figure. Thank you!

**Comment by mcmero** [comment]
Unfortunately, this is quite tricky as we were not able to make the results public as these are controlled data. The ICGC data portal holds the [PCAWG subclonal reconstruction data](https://dcc.icgc.org/releases/PCAWG/subclonal_reconstruction), however, you will have to apply for access via the DACO. This includes subclonal SV data, but using consensus methods rather than SVclone/ccube, so the CCFs won't be completely identical.

**Comment by shwong-tw** [comment]
Hi, thanks for getting back.
Please correct me if my understanding is not correct,
but sample-wise subclonal fraction is a summary statistic and does not reveal private genetic information.
Therefore it is not part of the controlled access data (variant calls, bam files, etc.).
Even clinical information of ICGC samples were public :)

**Comment by mcmero** [comment]
Figure 6b was generated using clinical information. You are correct about subclonal fractions being a summary statistic, however, data access was coordinated by the PCAWG consortium, so we were not able to independently release these data.

**Comment by shwong-tw** [comment]
I see, thanks for the elaboration :)
Then is it possible to release the Fig. 6b classification (which sample belongs to which subgroup),
hopefully this is nothing related to subclonal fraction per se and therefore acceptable.
